version: "3.8"

services:
  app:
    build: .
    ports:
      - "8888:8888"
    env_file:
      - .env
    volumes:
      - ./backend/database:/app/backend/database
      - ./backend/logs:/app/backend/logs
    restart: unless-stopped
